#!/bin/bash

EXTRA_ARGS=$@

rm -f CMakeCache.txt

cmake \
 -D CMAKE_VERBOSE_MAKEFILE:BOOL=ON \
 -D CMAKE_CXX_COMPILER:STRING=/usr/local/bin/mpic++ \
 -D CMAKE_C_COMPILER:STRING=/usr/local/bin/mpicc \
 -D CMAKE_EXE_LINKER_FLAGS:STRING="-L/opt/local/lib" \
 -D KANOMI_TRILINOS_DIR:FILEPATH=/usr/local/trilinos-master/mpi/opt \
 $EXTRA_ARGS ..
