#ifndef KANOMI_FIELDNAMES_HPP_
#define KANOMI_FIELDNAMES_HPP_

#include <Kanomi_Named.hpp>

namespace kanomi {
namespace field {

KANOMI_NAMED_TAG( BASIS_FUNCTION );
KANOMI_NAMED_TAG( DETJ );
KANOMI_NAMED_TAG( ENERGY_RESIDUAL );
KANOMI_NAMED_TAG( GRAD_BASIS_FUNCTION );
KANOMI_NAMED_TAG( GRAD_TEMPERATURE );
KANOMI_NAMED_TAG( TEMPERATURE );
KANOMI_NAMED_TAG( THERMAL_CONDUCTIVITY );
KANOMI_NAMED_TAG( QUADRATURE_WEIGHTS );

}
} // namespace kanomi

#endif /* KANOMI_FIELDNAMES_HPP_ */
